package com.miaoshaproject.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrep_password
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    private String encrepPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrep_password
     *
     * @return the value of user_password.encrep_password
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    public String getEncrepPassword() {
        return encrepPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrep_password
     *
     * @param encrepPassword the value for user_password.encrep_password
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    public void setEncrepPassword(String encrepPassword) {
        this.encrepPassword = encrepPassword == null ? null : encrepPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Wed Jul 15 20:07:09 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}